version: "2"

services:
  haproxy:
    image: bobfraser1/haproxy-env
    environment:
      - "constraint:com.bobfraser1.apptier==frontend"
      - "HAPROXY_MODE=http"
      - "HAPROXY_BIND_PORT=80"
      - "HAPROXY_BACKEND=nginx:80"
    ports:
      - "80:80"
    networks:
      - nginx-app
  nginx:
    image: nginx:alpine
    environment:
      - "constraint:com.bobfraser1.apptier==data"
    expose:
      - "80"
    volumes:
      - nginx-app-html:/usr/share/nginx/html
    networks:
      - nginx-app
volumes:
  nginx-app-html:
    external: true
networks:
  nginx-app:
